//
//  NewsFeedListInterfaces.swift
//  EndavaTest
//
//  Created by Danijel Kecman on 8/3/17.
//  Copyright (c) 2017 Danijel Kecman. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

enum NewsFeedListNavigationOption {
    case articleDetails(article: Article)
}

protocol NewsFeedListWireframeInterface: WireframeInterface {
    func navigate(to option: NewsFeedListNavigationOption)
}

protocol NewsFeedListViewInterface: ViewInterface, Progressable, Alertable {
    func reloadTable()
}

protocol NewsFeedListPresenterInterface: PresenterInterface {
    // Data Source and Delegate
    func numberOfNewsSections() -> Int
    func numberOfNews(in section: Int) -> Int
    func newsFeedItem(at indexPath: IndexPath) -> NewsFeedItem
    func didSelectNewsItem(at indexPath: IndexPath)
    // Actions
    func refreshFeed()
    
}

protocol NewsFeedListInteractorInterface: InteractorInterface {
    func getNewsFeedListFrom(source: String, completion: @escaping ([Article]) -> Void)
}

