//
//  NewsFeedListViewController.swift
//  EndavaTest
//
//  Created by Danijel Kecman on 8/3/17.
//  Copyright (c) 2017 Danijel Kecman. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit
import Reusable

final class NewsFeedListViewController: UIViewController {
    
    @IBOutlet weak var tableView: UITableView!

    // MARK: - Public properties -

    var presenter: NewsFeedListPresenterInterface!

    // MARK: - Lifecycle -

    override func viewDidLoad() {
        super.viewDidLoad()
        
        _configure()
        presenter.viewDidLoad()
    }
	
    // MARK: - Private functions -
    
    private func _configure() {
        // Navigation bar setup
        let refreshButton = UIBarButtonItem(barButtonSystemItem: .refresh, target: self, action: #selector(_refreshFeed))
        navigationItem.rightBarButtonItem = refreshButton
        
        // TableView setup
        tableView.register(cellType: NewsFeedCell.self)
        tableView.rowHeight = UITableViewAutomaticDimension
        tableView.estimatedRowHeight = 80
    }
    
    // MARK: - Actions -
    
    func _refreshFeed() {
        presenter.refreshFeed()
    }
}

// MARK: - Table Data Source -

extension NewsFeedListViewController: UITableViewDataSource, UITableViewDelegate {
    
    func numberOfSections(in tableView: UITableView) -> Int {
        return presenter.numberOfNewsSections()
    }
    
    func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        return presenter.numberOfNews(in: section)
    }
    
    func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        let item = presenter.newsFeedItem(at: indexPath)
        
        let cell: NewsFeedCell = tableView.dequeueReusableCell(for: indexPath)
        cell.configure(with: item)
        
        return cell
    }
    
    func tableView(_ tableView: UITableView, didSelectRowAt indexPath: IndexPath) {
        presenter.didSelectNewsItem(at: indexPath)
    }
    
}

// MARK: - Extensions -

extension NewsFeedListViewController: NewsFeedListViewInterface {
    func reloadTable() {
        tableView.reloadData()
    }
}









