//
//  NewsSourcesInterfaces.swift
//  EndavaTest
//
//  Created by Danijel Kecman on 8/4/17.
//  Copyright (c) 2017 Danijel Kecman. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

enum NewsSourcesNavigationOption {
    case newsFeed(source: String)
}

protocol NewsSourcesWireframeInterface: WireframeInterface {
    func navigate(to option: NewsSourcesNavigationOption)
}

protocol NewsSourcesViewInterface: ViewInterface, Progressable, Alertable {
    func reloadTable()
}

protocol NewsSourcesPresenterInterface: PresenterInterface {
    // Data Source and Delegate
    func numberOfSourcesSections() -> Int
    func numberOfSources(in section: Int) -> Int
    func sourceItem(at indexPath: IndexPath) -> SourceItem
    func didSelectSourceItem(at indexPath: IndexPath)
    // Actions
    func refreshSources()
}

protocol NewsSourcesInteractorInterface: InteractorInterface {
    func getSourcesList(completion: @escaping ([Source]) -> Void)
}
