//
//  NewsSourcesInteractor.swift
//  EndavaTest
//
//  Created by Danijel Kecman on 8/4/17.
//  Copyright (c) 2017 Danijel Kecman. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation
import Alamofire
import SwiftyJSON

final class NewsSourcesInteractor {
}

// MARK: - Extensions -

extension NewsSourcesInteractor: NewsSourcesInteractorInterface {
    func getSourcesList(completion: @escaping ([Source]) -> Void) {
        SessionManager.default.request(Router.newsSource(language: "en")).responseData { response in
            if response.error != nil {
                print(response.error!.localizedDescription)
                return
            }
            
            let json = JSON(data: response.data!)
            let sourcesJson = json["sources"]
            
            var sources = [Source]()
            for (_, sourceJson) in sourcesJson {
                let source = Source(id: sourceJson["id"].string!,
                                    name: sourceJson["name"].string!,
                                    description: sourceJson["description"].string!,
                                    category: sourceJson["category"].string!)
                
                sources.append(source)
            }
            completion(sources)
        }
    }

}
