//
//  NewsSourcesViewController.swift
//  EndavaTest
//
//  Created by Danijel Kecman on 8/4/17.
//  Copyright (c) 2017 Danijel Kecman. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class NewsSourcesViewController: UIViewController {
    
    @IBOutlet weak var tableView: UITableView!

    // MARK: - Public properties -

    var presenter: NewsSourcesPresenterInterface!

    // MARK: - Lifecycle -

    override func viewDidLoad() {
        super.viewDidLoad()
        
        _configure()
        presenter.viewDidLoad()
    }
    
    // MARK: - Private methods -
    
    func _configure() {
        // Navigation bar setup
        let refreshButton = UIBarButtonItem(barButtonSystemItem: .refresh, target: self, action: #selector(_refreshSources))
        navigationItem.rightBarButtonItem = refreshButton
        
        // TableView setup
        tableView.register(cellType: SourceCell.self)
    }
    
    // MARK: - Actions -
    
    func _refreshSources() {
        presenter.refreshSources()
    }
	
}

// MARK: - Table Data Source -

extension NewsSourcesViewController: UITableViewDataSource, UITableViewDelegate {
    
    func numberOfSections(in tableView: UITableView) -> Int {
        return presenter.numberOfSourcesSections()
    }
    
    func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        return presenter.numberOfSources(in: section)
    }
    
    func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        let item = presenter.sourceItem(at: indexPath)
        
        let cell: SourceCell = tableView.dequeueReusableCell(for: indexPath)
        cell.configure(with: item)
        
        return cell
    }
    
    func tableView(_ tableView: UITableView, didSelectRowAt indexPath: IndexPath) {
        presenter.didSelectSourceItem(at: indexPath)
    }
    
}

// MARK: - Extensions -

extension NewsSourcesViewController: NewsSourcesViewInterface {
    func reloadTable() {
        tableView.reloadData()
    }
}
