//
//  NewsDetailsInteractor.swift
//  EndavaTest
//
//  Created by Danijel Kecman on 8/4/17.
//  Copyright (c) 2017 Danijel Kecman. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class NewsDetailsInteractor {
}

// MARK: - Extensions -

extension NewsDetailsInteractor: NewsDetailsInteractorInterface {
}
