//
//  NewsDetailsWireframe.swift
//  EndavaTest
//
//  Created by Danijel Kecman on 8/4/17.
//  Copyright (c) 2017 Danijel Kecman. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class NewsDetailsWireframe: BaseWireframe {

    // MARK: - Private properties -

    private let _storyboard: UIStoryboard = UIStoryboard(name: "Main", bundle: nil)

    // MARK: - Module setup -

    func configureModule(with viewController: NewsDetailsViewController, article: Article) {
        let interactor = NewsDetailsInteractor()
        let presenter = NewsDetailsPresenter(wireframe: self, view: viewController, interactor: interactor, article: article)
        viewController.presenter = presenter
    }

    // MARK: - Transitions -

    func show(with transition: Transition, animated: Bool = true, article: Article) {
        let moduleViewController = _storyboard.instantiateViewController(withIdentifier: "NewsDetailsViewController") as! NewsDetailsViewController
        configureModule(with: moduleViewController, article: article)

        show(moduleViewController, with: transition, animated: animated)
    }
}

// MARK: - Extensions -

extension NewsDetailsWireframe: NewsDetailsWireframeInterface {

    func navigate(to option: NewsDetailsNavigationOption) {
    }
}
