//
//  NewsDetailsViewController.swift
//  EndavaTest
//
//  Created by Danijel Kecman on 8/4/17.
//  Copyright (c) 2017 Danijel Kecman. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class NewsDetailsViewController: UIViewController {

    @IBOutlet weak var articleImage: UIImageView!
    @IBOutlet weak var articleAuthor: UILabel!
    @IBOutlet weak var articleTitle: UILabel!
    @IBOutlet weak var articleDescription: UILabel!
    @IBOutlet weak var articlePublishedAt: UILabel!
    
    
    // MARK: - Public properties -

    var presenter: NewsDetailsPresenterInterface!

    // MARK: - Lifecycle -

    override func viewDidLoad() {
        super.viewDidLoad()
        
        _configure()
        presenter.viewDidLoad()
    }
    
    // MARL: - Private Methods -
    
    private func _configure() {
        
    }
	
}

// MARK: - Extensions -

extension NewsDetailsViewController: NewsDetailsViewInterface {
    func showArticle(article: Article) {
        articleTitle.text = article.title
        articleAuthor.text = article.author
        articleDescription.text = article.description
        articlePublishedAt.text = article.publishedAt
        articleImage.image(from: article.imageUrl)
        
        articleDescription.sizeToFit()
    }
}
